name: GitHub Readme YouTube Thumbnails
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/youtube-cards.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # allows updating README

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate YouTube thumbnails
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UC8dhutoCJKLHVxDzg0gaQvg
          comment_tag_name: YOUTUBE-CARDS
          output_type: markdown   # output as plain markdown (no cards)
          show_duration: false    # no API key needed
