name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/youtube-cards.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # ðŸ‘ˆ allows push to repo

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UC8dhutoCJKLHVxDzg0gaQvg
          comment_tag_name: YOUTUBE-CARDS
          max_title_lines: 2
          show_duration: false
          output_type: html
